#!/usr/bin/env python3
"""C5 numerical falsification of the corrected full three-firm price profiles.

The program discretizes the Salop circle and computes each firm's global
unilateral best response from the exact delivered-price threshold against the
other two firms.  This avoids a local price search.  The small positive member
"gain" produced by discretization is required to lie below a pre-specified
Riemann-grid error bound and to shrink under a higher-resolution convergence
check.
"""
import numpy as np

REPRESENTATIVE_C = [
    2.5001, 2.51, 2.60, 2.75, 2.90, 2.99, 2.9999,
    3.00, 3.0001, 3.10, 3.50, 4.00, 4.50, 4.90, 4.999,
]
# Dense grids in the two post-foreclosure regions.
DENSE_C = np.concatenate([
    np.linspace(2.5001, 2.9999, 151),
    np.array([3.0]),
    np.linspace(3.0001, 4.999, 301),
])


def geometry(n):
    x = (np.arange(n) + 0.5) * 3.0 / n
    loc = np.array([0.0, 1.0, 2.0])
    dist = np.abs(x[:, None] - loc[None, :])
    return np.minimum(dist, 3.0 - dist) ** 2


def candidate(c):
    if c < 3.0:
        return np.array([c - 1.0, c - 1.0, c])
    return np.array([2.0, 2.0, c])


def candidate_profit(i, c):
    if i == 0:
        return 1.5 * candidate(c)[0]
    return 0.0


def global_best_response(i, marginal_cost, prices, dist2):
    """Best unilateral profit on the discretized circle over all real prices.

    A consumer buys from i when p_i is below the delivered-price threshold
    generated by the lower envelope of the other firms.  Sorting those
    thresholds evaluates every demand discontinuity and hence the global best
    response on the discretized market.  A zero-demand price guarantees profit 0.
    """
    others = [j for j in range(3) if j != i]
    threshold = (
        np.minimum(
            prices[others[0]] + dist2[:, others[0]],
            prices[others[1]] + dist2[:, others[1]],
        )
        - dist2[:, i]
    )
    s = np.sort(threshold)[::-1]
    k = np.arange(1, len(s) + 1, dtype=float)
    q = k * (3.0 / len(s))
    profit = (s - marginal_cost) * q
    idx = int(np.argmax(profit))
    best_profit = max(0.0, float(profit[idx]))
    return best_profit, float(s[idx]), float(q[idx])


def run_grid(n, c_grid):
    dist2 = geometry(n)
    max_member_gain = -np.inf
    max_outsider_gain = -np.inf
    worst_member = None
    worst_outsider = None
    rows = []
    for c in c_grid:
        p = candidate(float(c))
        bm, bpm, bqm = global_best_response(0, 0.0, p, dist2)
        bo, bpo, bqo = global_best_response(2, float(c), p, dist2)
        mg = bm - candidate_profit(0, float(c))
        og = bo  # candidate outsider profit is zero
        if mg > max_member_gain:
            max_member_gain = mg
            worst_member = (float(c), bpm, bqm, bm)
        if og > max_outsider_gain:
            max_outsider_gain = og
            worst_outsider = (float(c), bpo, bqo, bo)
        rows.append((float(c), mg, og))
    return max_member_gain, max_outsider_gain, worst_member, worst_outsider, rows


# Main dense falsification at high resolution.
N_FINE = 80000
fine = run_grid(N_FINE, DENSE_C)
max_member_gain, max_outsider_gain, worst_member, worst_outsider, _ = fine
# Conservative ex-ante discretization allowance: one spatial cell times a
# maximum economically relevant price of 5, multiplied by 4 for boundary/tie
# effects.  It is fixed by resolution, not calibrated to the observed result.
DX_FINE = 3.0 / N_FINE
DISCRETIZATION_BOUND = 4.0 * 5.0 * DX_FINE
if max_member_gain > DISCRETIZATION_BOUND:
    raise AssertionError(
        f"dense member counterexample: gain={max_member_gain}, "
        f"bound={DISCRETIZATION_BOUND}, worst={worst_member}"
    )
if max_outsider_gain > 1e-10:
    raise AssertionError(
        f"dense outsider counterexample: gain={max_outsider_gain}, "
        f"worst={worst_outsider}"
    )

# Convergence check: the discretization artifact must shrink materially when N
# rises from 20,000 to 80,000.
coarse = run_grid(20000, DENSE_C[::4])
if max_member_gain >= 0.40 * coarse[0]:
    raise AssertionError(
        f"discretization gain did not shrink: coarse={coarse[0]}, fine={max_member_gain}"
    )

print(f"PASS dense grid: {len(DENSE_C)} c-values on [2.5001, 4.999]")
print(
    "PASS global member deviations: "
    f"max discretized apparent gain={max_member_gain:.8g} "
    f"< fixed grid bound={DISCRETIZATION_BOUND:.8g}; worst={worst_member}"
)
print(
    "PASS outsider deviations (including below-cost candidate thresholds): "
    f"max profitable gain={max_outsider_gain:.8g}; worst={worst_outsider}"
)
print(
    "PASS convergence: apparent member gain shrinks from "
    f"{coarse[0]:.8g} at N=20000 to {max_member_gain:.8g} at N={N_FINE}"
)

# Representative points for human-readable diagnostics.
dist_rep = geometry(N_FINE)
for c in REPRESENTATIVE_C:
    p = candidate(c)
    bm, bpm, bqm = global_best_response(0, 0.0, p, dist_rep)
    bo, bpo, bqo = global_best_response(2, c, p, dist_rep)
    print(
        f"PASS c={c:6.4f}: pM={p[0]:.4f}; "
        f"member best approx p={bpm:.5f}, gain={bm-candidate_profit(0,c):.7f}; "
        f"outsider max profit={bo:.7f}"
    )

# Exact c=4 illustration using the analytical demand formula while outsider is
# foreclosed; this is deliberately not a discretized equality check.
base = 1.5 * 1.5
dev_q = 1.5 + 0.75 * (1.5 - 1.75)
dev = 1.75 * dev_q
if abs(base - 2.25) > 1e-12 or abs(dev - 2.296875) > 1e-12 or dev <= base:
    raise AssertionError(f"c=4 counterexample failed: base={base}, dev={dev}")
print(f"PASS c=4 published-profile counterexample: {base:.6f} -> {dev:.6f}, gain={dev-base:.6f}")
print("All dense numerical falsification checks passed.")
